title: "ExCaLBBR Lab"
author: "Roberto Vargas"
description: "Carnegie Mellon University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "People"}
  - {file: "README.md", title: "Values"}
  - {title: "Code", url: "https://github.com/ExCaLBBR/ExCaLBBR_Projects"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:excalbbr@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/ExCaLBBR/ExCaLBBR_Projects"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
